### ISSUE TITLE
Proposal to introduce pre-commit

### ISSUE THREAD

**Issue by dc7303** [yorkie-team/yorkie-rust-sdk#6]
**Description**:
Rust can run `cargo fmt` to clean up your code. If all developers make this a habit, our code will be relatively clean.

So I'd like to make a suggestion. How about forcing `cargo fmt -- --check` when committing by introducing `pre-commit`?

**Why**:
For consistent code conventions!

**Comment by hackerwins** [comment]
@dc7303 Thanks for the good opinion.

First of all, I added `cargo fmt` to CI to keep the code clean: https://github.com/yorkie-team/yorkie-rust-sdk/commit/8ad45d0579faa35df9457c8603bd139783eec2ac

How can we introduce `cargo fmt -- --check` in pre-commit? Do we need to provide guides to users or can we introduce a library like Husky in [JS SDK](https://github.com/yorkie-team/yorkie-js-sdk/blob/776c73c8636fb270f126f3c7d1e1c280ea426d20/package.json#L87-L91)?

**Comment by dc7303** [comment]
@hackerwins I was thinking of [pre-commit](https://pre-commit.com/). There is a problem with having to do a pre-commit installation, but I think it's a good alternative for now.

I don't know much about pre-commit yet, but it seems to be used a lot. So I'm going to investigate this a bit more. If you have any other good ideas, please suggest them :D

**Comment by hackerwins** [comment]
@dc7303 I think we can keep our code clean by adding `cargo fmt` to CI. pre-commit is a useful tool, but I don't think it's necessary to force it for development, what do you think?

**Comment by dc7303** [comment]
@dc7303 Oh! We're already using that in Yorkie, and I'm stupid I didn't think of that. That looks a lot better. 👍

**Comment by dc7303** [comment]
Looks like this could be close.
