### ISSUE TITLE
Add json.primitive

### ISSUE THREAD

**Issue by dc7303** [yorkie-team/yorkie-rust-sdk#7]
**Description**:
Add primitive of json package.

ref [https://github.com/yorkie-team/yorkie/blob/main/pkg/document/json/primitive.go](https://github.com/yorkie-team/yorkie/blob/main/pkg/document/json/primitive.go)

**Why**:

**Comment by mojosoeun** [comment]
Can I try this issue?

**Comment by hackerwins** [comment]
Since this is an old issue, I'll close it for now.
